<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>net.nick4name.MergeService</RootNamespace>
    <AssemblyVersion>1.25.11.1</AssemblyVersion>
    <FileVersion>1.25.11.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="IMerge.cs" />
    <Compile Remove="IMergeDocType.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="net.nick4name.MergeExtensions">
      <HintPath>..\..\..\..\..\MyPrograms\COMMON_BETA\HostHouse\net.nick4name.MergeExtensions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
